version: 2

sources:
  - name: raw
    schema: raw

    tables:
      - name: customers
        description: "Raw customer data from operational system"
        loaded_at_field: _ingested_at
        freshness:
          warn_after: { count: 30, period: minute }
          error_after: { count: 2, period: hour }
        config:
          meta:
            dagster:
              asset_key: ["ingestion_customers"]

      - name: products
        description: "Raw product catalog"
        loaded_at_field: _ingested_at
        freshness:
          warn_after: { count: 30, period: minute }
          error_after: { count: 2, period: hour }
        config:
          meta:
            dagster:
              asset_key: ["ingestion_products"]

      - name: orders
        description: "Raw order transactions"
        loaded_at_field: _ingested_at
        freshness:
          warn_after: { count: 30, period: minute }
          error_after: { count: 2, period: hour }
        config:
          meta:
            dagster:
              asset_key: ["ingestion_orders"]

      - name: orders__items
        description: "Raw order line items (generated with orders)"
        loaded_at_field: _ingested_at
        freshness:
          warn_after: { count: 30, period: minute }
          error_after: { count: 2, period: hour }
        config:
          meta:
            dagster:
              asset_key: ["ingestion_orders"]